# src/report_pdf.py

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    PageBreak,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.units import mm
import itertools

APP_NAME = "IBKR Tax Assistant"
APP_VERSION = "v2.2.0"


def get_zebra_style(row_count, header_color=colors.HexColor("#D0D0D0")):
    """Creates a striped table style with a sticky header."""
    cmds = [
        ("BACKGROUND", (0, 0), (-1, 0), header_color),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
        ("ALIGN", (0, 0), (-1, 0), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ALIGN", (0, 1), (0, -1), "CENTER"),
    ]
    for i in range(1, row_count):
        if i % 2 == 0:
            cmds.append(("BACKGROUND", (0, i), (-1, i), colors.HexColor("#F0F0F0")))
    return TableStyle(cmds)


def add_footer(canvas, doc):
    """Draws page numbers and a warning legend on every page."""
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(colors.grey)
    footer_text = f"Generated by {APP_NAME} {APP_VERSION}"
    canvas.drawString(10 * mm, 10 * mm, footer_text)
    
    # Legend for the zero-cost warning marker
    canvas.setFont("Helvetica-Oblique", 7)
    canvas.drawRightString(A4[0] - 10 * mm, 14 * mm, "(!) Warning: Acquisition price is 0.00. Check manual_fixes.csv.")
    
    canvas.setFont("Helvetica", 8)
    page_num = f"Page {doc.page}"
    canvas.drawRightString(A4[0] - 10 * mm, 10 * mm, page_num)
    canvas.setStrokeColor(colors.lightgrey)
    canvas.line(10 * mm, 14 * mm, A4[0] - 10 * mm, 14 * mm)
    canvas.restoreState()


def generate_pdf(json_data, filename="report.pdf"):
    """Main function to build the multi-page tax report."""
    doc = SimpleDocTemplate(
        filename,
        pagesize=A4,
        bottomMargin=20 * mm,
        topMargin=20 * mm,
        leftMargin=10 * mm,
        rightMargin=10 * mm,
    )
    elements = []
    styles = getSampleStyleSheet()

    year = json_data["year"]
    data = json_data["data"]

    # --- STYLES DEFINITION ---
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=24,
        spaceAfter=20,
        alignment=TA_CENTER,
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle", parent=styles["Normal"], fontSize=12, alignment=TA_CENTER
    )
    h2_style = ParagraphStyle(
        "H2Centered",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        spaceAfter=12,
        spaceBefore=18,
    )
    h3_style = ParagraphStyle(
        "H3Centered",
        parent=styles["Heading3"],
        alignment=TA_CENTER,
        spaceAfter=8,
        spaceBefore=4,
    )
    normal_style = styles["Normal"]
    italic_small = ParagraphStyle(
        "ItalicSmall", parent=styles["Italic"], fontSize=8, alignment=TA_LEFT
    )

    # PAGE 1: COVER PAGE
    elements.append(Spacer(1, 50))
    elements.append(Paragraph(f"Tax report — {year}", title_style))
    elements.append(Spacer(1, 10))
    elements.append(
        Paragraph(f"Report period: 01-01-{year} - 31-12-{year}", subtitle_style)
    )
    elements.append(PageBreak())

    # PAGE 2: PORTFOLIO COMPOSITION
    elements.append(
        Paragraph(f"Portfolio Composition (as of Dec 31, {year})", h2_style)
    )
    if data["holdings"]:
        holdings_data = [["#", "Ticker", "Quantity", "FIFO Check"]]
        restricted_indices = []
        has_restricted = False

        row_idx = 1
        for h in data["holdings"]:
            display_ticker = h["ticker"]
            if h.get("is_restricted", False):
                display_ticker += " *"
                has_restricted = True
                restricted_indices.append(row_idx)

            # Mark OK with (!) if cost basis is zero (like for Spinoffs)
            check_mark = "OK" if h.get("fifo_match", False) else "MISMATCH!"
            if h.get("fifo_match", False) and h.get("cost_basis", 1) == 0:
                check_mark = "OK (!)"

            holdings_data.append(
                [str(row_idx), display_ticker, f"{h['qty']:.4f}", check_mark]
            )
            row_idx += 1

        t_holdings = Table(holdings_data, colWidths=[30, 180, 100, 100], repeatRows=1)
        ts = get_zebra_style(len(holdings_data))
        ts.add("ALIGN", (2, 1), (2, -1), "RIGHT")
        ts.add("ALIGN", (3, 1), (3, -1), "CENTER")

        for i, row in enumerate(holdings_data[1:], start=1):
            if "MISMATCH" in row[3]:
                ts.add("TEXTCOLOR", (3, i), (3, i), colors.red)
            elif "(!)" in row[3]:
                ts.add("TEXTCOLOR", (3, i), (3, i), colors.orange)

        for r_idx in restricted_indices:
            ts.add("BACKGROUND", (0, r_idx), (-1, r_idx), colors.HexColor("#FFCCCC"))

        t_holdings.setStyle(ts)
        elements.append(t_holdings)

        if has_restricted:
            elements.append(Spacer(1, 10))
            elements.append(
                Paragraph("* Assets held in special escrow accounts / sanctioned (RUB)", italic_small)
            )
    else:
        elements.append(Paragraph("No open positions found.", normal_style))
    elements.append(PageBreak())

    # PAGE 3: TRADES HISTORY
    elements.append(Paragraph(f"Trades History ({year})", h2_style))
    if data["trades_history"]:
        trades_header = [["#", "Date", "Ticker", "Type", "Qty", "Price", "Comm", "Curr"]]
        trades_rows = []

        for i, t in enumerate(data["trades_history"], 1):
            price_val = t.get("price", 0)
            price_display = f"{price_val:.2f}"
            if price_val == 0:
                price_display += " (!)"

            row = [
                str(i), t["date"], t["ticker"], t.get("type", "UNKNOWN"),
                f"{abs(t['qty']):.4f}", price_display,
                f"{t['commission']:.2f}", t["currency"]
            ]
            trades_rows.append(row)

        full_table_data = trades_header + trades_rows
        col_widths = [25, 60, 50, 50, 50, 50, 50, 40]
        t_trades = Table(full_table_data, colWidths=col_widths, repeatRows=1)
        ts_trades = get_zebra_style(len(full_table_data))
        ts_trades.add("ALIGN", (4, 1), (-1, -1), "RIGHT")
        
        for i, row in enumerate(trades_rows, 1):
            if "(!)" in row[5]:
                ts_trades.add("TEXTCOLOR", (5, i), (5, i), colors.orange)

        t_trades.setStyle(ts_trades)
        elements.append(t_trades)
    else:
        elements.append(Paragraph("No trades executed this year.", normal_style))

    # PAGE: CORPORATE ACTIONS
    if data["corp_actions"]:
        elements.append(PageBreak())
        elements.append(Paragraph(f"Corporate Actions & Splits ({year})", h2_style))
        corp_header = [["#", "Date", "Ticker", "Type", "Details"]]
        corp_rows = []

        for i, act in enumerate(data["corp_actions"], 1):
            details = ""
            warning = " (!)" if act.get("price", 0) == 0 else ""
            
            if act["type"] == "SPLIT":
                ratio = act.get("ratio", 1)
                details = f"Split Ratio: {ratio:.4f}"
            elif act["type"] in ["STOCK_DIV", "SPINOFF"] or act.get("source") == "IBKR_CORP_ACTION":
                details = f"Stock/Spin: +{act['qty']:.4f}{warning}"
            elif act["type"] == "MERGER":
                details = f"Merger/Liq: {act['qty']:.4f}{warning}"
            elif act["type"] == "TRANSFER":
                details = f"Adjustment: {act['qty']:.4f}{warning}"
            else:
                details = f"Other Adjustment{warning}"

            corp_rows.append([str(i), act["date"], act["ticker"], act["type"], details])

        full_corp_data = corp_header + corp_rows
        t_corp = Table(full_corp_data, colWidths=[25, 75, 60, 70, 200], repeatRows=1)
        ts_corp = get_zebra_style(len(full_corp_data))
        for i, row in enumerate(corp_rows, 1):
            if "(!)" in row[4]:
                ts_corp.add("TEXTCOLOR", (4, i), (4, i), colors.orange)
        t_corp.setStyle(ts_corp)
        elements.append(t_corp)

    elements.append(PageBreak())

    # PAGE 4: MONTHLY DIVIDENDS SUMMARY
    elements.append(Paragraph(f"Monthly Dividends Summary ({year})", h2_style))
    month_names = {
        "01": "January", "02": "February", "03": "March", "04": "April",
        "05": "May", "06": "June", "07": "July", "08": "August",
        "09": "September", "10": "October", "11": "November", "12": "December",
    }

    if data["monthly_dividends"]:
        m_data = [["#", "Month", "Gross (PLN)", "Tax Paid (PLN)", "Net (PLN)"]]
        sorted_months = sorted(data["monthly_dividends"].keys())
        total_gross, total_tax = 0, 0

        for i, m in enumerate(sorted_months, 1):
            vals = data["monthly_dividends"][m]
            m_data.append([
                str(i), month_names.get(m, m),
                f"{vals['gross_pln']:,.2f}", f"{vals['tax_pln']:,.2f}", f"{vals['net_pln']:,.2f}",
            ])
            total_gross += vals["gross_pln"]
            total_tax += vals["tax_pln"]

        m_data.append(["", "TOTAL", f"{total_gross:,.2f}", f"{total_tax:,.2f}", f"{total_gross - total_tax:,.2f}"])

        t_months = Table(m_data, colWidths=[25, 90, 100, 100, 100], repeatRows=1)
        ts = get_zebra_style(len(m_data))
        ts.add("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold")
        ts.add("BACKGROUND", (0, -1), (-1, -1), colors.lightgrey)
        ts.add("ALIGN", (2, 1), (-1, -1), "RIGHT")
        t_months.setStyle(ts)
        elements.append(t_months)

        # --- DETAILED DIVIDENDS ---
        elements.append(PageBreak())
        elements.append(Paragraph(f"Dividend Details (Chronological)", h2_style))
        elements.append(Paragraph("Detailed breakdown of every dividend payment received.", normal_style))
        elements.append(Spacer(1, 10))

        sorted_divs = sorted(data["dividends"], key=lambda x: x["date"])
        is_first_month = True
        global_div_idx = 1

        for month_key, group in itertools.groupby(sorted_divs, key=lambda x: x["date"][:7]):
            if not is_first_month: elements.append(PageBreak())
            is_first_month = False

            y, m = month_key.split("-")
            elements.append(Paragraph(f"{month_names.get(m, m)} {y}", h2_style))

            det_header = [["#", "Date", "Ticker", "Gross", "Rate", "Gross PLN", "Tax PLN"]]
            det_rows = []
            for d in group:
                det_rows.append([
                    str(global_div_idx), d["date"], d["ticker"],
                    f"{d['amount']:.2f} {d['currency']}", f"{d['rate']:.4f}",
                    f"{d['amount_pln']:.2f}", f"{d['tax_paid_pln']:.2f}",
                ])
                global_div_idx += 1

            t_det = Table(det_header + det_rows, colWidths=[25, 60, 45, 80, 45, 65, 65], repeatRows=1)
            ts_det = get_zebra_style(len(det_header + det_rows))
            ts_det.add("ALIGN", (3, 1), (-1, -1), "RIGHT")
            t_det.setStyle(ts_det)
            elements.append(t_det)
    else:
        elements.append(Paragraph("No dividends received this year.", normal_style))

    elements.append(PageBreak())

    # PAGE: YEARLY SUMMARY
    elements.append(Paragraph(f"Yearly Summary", h2_style))
    div_gross = sum(x["amount_pln"] for x in data["dividends"])
    div_tax = sum(x["tax_paid_pln"] for x in data["dividends"])
    polish_tax_due = max(0, (div_gross * 0.19) - div_tax)
    final_net = div_gross - div_tax - polish_tax_due

    summary_data = [
        ["Metric", "Amount (PLN)"],
        ["Total Dividends", f"{div_gross:,.2f}"],
        ["Withheld Tax (sum)", f"-{div_tax:,.2f}"],
        ["Additional Tax (PL, ~diff)", f"{polish_tax_due:,.2f}"],
        ["Final Net (after full 19%)", f"{final_net:,.2f}"],
    ]
    t_summary = Table(summary_data, colWidths=[250, 150])
    ts_sum = get_zebra_style(len(summary_data))
    ts_sum.add("ALIGN", (1, 1), (-1, -1), "RIGHT")
    t_summary.setStyle(ts_sum)
    elements.append(t_summary)

    # DIAGNOSTICS
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Diagnostics", h2_style))
    diag = data["diagnostics"]
    diag_data = [
        ["Indicator", "Value"],
        ["Tickers (unique)", str(diag["tickers_count"])],
        ["Dividend rows", str(diag["div_rows_count"])],
        ["Tax rows", str(diag["tax_rows_count"])],
    ]
    t_diag = Table(diag_data, colWidths=[250, 150])
    ts_diag = get_zebra_style(len(diag_data))
    ts_diag.add("ALIGN", (1, 1), (-1, -1), "CENTER")
    t_diag.setStyle(ts_diag)
    elements.append(t_diag)

    # PER-CURRENCY
    elements.append(Spacer(1, 20))
    elements.append(Paragraph("Per-currency totals (PLN)", h2_style))
    curr_data = [["Currency", "PLN total"]]
    for curr, val in data["per_currency"].items():
        curr_data.append([curr, f"{val:,.2f}"])
    t_curr = Table(curr_data, colWidths=[250, 150], repeatRows=1)
    ts_curr = get_zebra_style(len(curr_data))
    ts_curr.add("ALIGN", (1, 1), (-1, -1), "RIGHT")
    t_curr.setStyle(ts_curr)
    elements.append(t_curr)
    elements.append(PageBreak())

    # PAGE: PIT-38 HELPER
    elements.append(Paragraph(f"PIT-38 Helper Data ({year})", h2_style))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph("Section C (Stocks/Derivatives)", h3_style))
    cap_rev = sum(x["revenue_pln"] for x in data["capital_gains"])
    cap_cost = sum(x["cost_pln"] for x in data["capital_gains"])
    pit_c_data = [
        ["Field in PIT-38", "Value (PLN)"],
        ["Przychód (Revenue) [Pos 20]", f"{cap_rev:,.2f}"],
        ["Koszty (Costs) [Pos 21]", f"{cap_cost:,.2f}"],
        ["Dochód/Strata", f"{cap_rev - cap_cost:,.2f}"],
    ]
    t_pit_c = Table(pit_c_data, colWidths=[250, 150])
    ts_pit = get_zebra_style(len(pit_c_data))
    ts_pit.add("ALIGN", (1, 1), (-1, -1), "RIGHT")
    t_pit_c.setStyle(ts_pit)
    elements.append(t_pit_c)
    elements.append(Spacer(1, 20))

    elements.append(Paragraph("Dividends (Foreign Tax)", h3_style))
    pit_div_data = [
        ["Description", "Value (PLN)"],
        ["Gross Income", f"{div_gross:,.2f}"],
        ["Tax Paid Abroad (Max deductible)", f"{div_tax:,.2f}"],
        ["TO PAY (Difference) [Pos 45]", f"{polish_tax_due:,.2f}"],
    ]
    t_pit_div = Table(pit_div_data, colWidths=[250, 150])
    ts_pit_div = get_zebra_style(len(pit_div_data))
    ts_pit_div.add("ALIGN", (1, 1), (-1, -1), "RIGHT")
    ts_pit_div.add("FONTNAME", (0, -1), (-1, -1), "Helvetica-Bold")
    t_pit_div.setStyle(ts_pit_div)
    elements.append(t_pit_div)

    doc.build(elements, onFirstPage=add_footer, onLaterPages=add_footer)